<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head><title>MSHC Portal: Change User Password</title></head>
<body>
<div style="max-width: 800px; margin: 0; padding: 30px 0;">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
<td align="left" style="font: 13px/18px Arial, Helvetica, sans-serif;">
<strong>This e-mail is notification of the following recent change to your Multi-Specialty Healthcare Attorney Portal account:</strong>
<br>
On <?php echo date('F j, Y at g:ia'); ?>  a request to reset your password was received by Multi-Specialty HealthCare’s Attorney Portal Support.
<br><br>
Your account credentials have been changed as follows:
<br /><br />
Username: <?php echo $username; ?>
<br />
New Password: <?php echo $password; ?>
<br /><br />
If you did not make this change or authorize someone else to make the change, contact the Multi-Specialty Healthcare Support Desk at 443-579-1101 immediately.
<br>
This email was automatically generated by the Multi-Specialty Attorney Portal. Please do not reply to this message.
<br><br>
<strong>Multi-Specialty HealthCare</strong>
<br><br>
This e-mail, including attachments, may include confidential and/or proprietary information, and may be used only by the person or entity to which it is addressed. This e-mail may also contain information which is confidential or which is protected from disclosure by federal HIPAA regulations. Any unauthorized use, disclosure or distribution of this e-mail and its attachments is prohibited. If you are not the intended recipient or believe you have received this e-mail in error, contact us immediately by reply e-mail and destroy all electronic or other copies of this message.
</td>
</tr>
</table>
</div>
</body>
</html>