This e-mail is notification of the following recent change to your Multi-Specialty Healthcare Attorney Portal account:

On <?php echo date('F j, Y at g:ia'); ?>  a request to reset your password was received by Multi-Specialty HealthCare’s Attorney Portal Support.

Your account credentials have been changed as follows:

Username: <?php echo $username; ?>
New Password: <?php echo $password; ?>

If you did not make this change or authorize someone else to make the change, contact the Multi-Specialty Healthcare Support Desk at 443-579-1101 immediately.
This email was automatically generated by the Multi-Specialty Attorney Portal. Please do not reply to this message.

Multi-Specialty HealthCare

This e-mail, including attachments, may include confidential and/or proprietary information, and may be used only by the person or entity to which it is addressed. This e-mail may also contain information which is confidential or which is protected from disclosure by federal HIPAA regulations. Any unauthorized use, disclosure or distribution of this e-mail and its attachments is prohibited. If you are not the intended recipient or believe you have received this e-mail in error, contact us immediately by reply e-mail and destroy all electronic or other copies of this message.